"""
@file scripts/vfpga/generator_gdb.py
@intent:responsibility
    DTS パース結果（BoardModel）を受け取り、GDB / LLDB 用の Python デバッガ拡張スクリプト（fbb_gdb.py）を自動生成する。
@intent:rationale
    FW 開発者が GDB または VS Code / Antigravity IDE のデバッグコンソールから、
    生アドレスの手計算を一切行うことなく、DTS 定義レジスタ名・ビットフィールド単位で
    MMIO レジスタの直感的な監視・書き込み（fbb-regs, fbb-write, fbb-fds, fbb-info）を行えるようにする。
"""

import json
from vfpga.models import BoardModel
from vfpga.generator_base import BaseGenerator


class GdbExtensionGenerator(BaseGenerator):
    """
    @class GdbExtensionGenerator
    @intent:responsibility
        DTS モデルから fbb_gdb.py を生成し、GDB Python API 連携カスタムコマンドを出力。
    """

    def generate(self, model: BoardModel) -> str:
        devices_data = []
        for dev in model.devices:
            regs_data = []
            for reg in dev.registers:
                try:
                    offset_val = int(str(reg.offset), 0)
                except (ValueError, TypeError):
                    offset_val = 0

                regs_data.append({
                    "name": reg.name,
                    "offset": offset_val,
                    "direction": getattr(reg, "direction", "RW").upper()
                })

            devices_data.append({
                "name": dev.name,
                "type": dev.type,
                "base_addr": getattr(dev, "base_addr", 0),
                "size": getattr(dev, "size", 0),
                "registers": regs_data
            })

        devices_json = json.dumps(devices_data, indent=4)
        model_name = getattr(model, "model_name", getattr(model, "name", "generic-vfpga"))
        shm_name = getattr(model, "name", "vfpga")

        script_content = f'''# Auto-generated GDB / LLDB Extension for FPGA-BoardlessBench (F-BB)
# Model: {model_name}
# Generated by scripts/vfpga/generator_gdb.py

import gdb
import struct
import sys
import os

FBB_MODEL_NAME = "{model_name}"
FBB_SHM_FILE = "/tmp/{shm_name}"
FBB_DEVICES = {devices_json}


class FbbRegsCommand(gdb.Command):
    """Print all F-BB MMIO registers defined in DTS with current memory values.
Usage: fbb-regs [device_name_or_filter]"""

    def __init__(self):
        super(FbbRegsCommand, self).__init__("fbb-regs", gdb.COMMAND_DATA)

    def invoke(self, arg, from_tty):
        filter_str = arg.strip().lower() if arg else ""
        inferior = gdb.selected_inferior() if hasattr(gdb, "selected_inferior") else None

        found_any = False
        for dev in FBB_DEVICES:
            if filter_str and (filter_str not in dev["name"].lower() and filter_str not in dev["type"].lower()):
                continue

            regs = dev.get("registers", [])
            if not regs and dev["base_addr"] == 0:
                continue

            found_any = True
            base_hex = f"0x{{dev['base_addr']:08X}}" if dev["base_addr"] else "N/A"
            print(f"\\n\\033[1;36m=== Device: {{dev['name']}} ({{dev['type']}}) @ {{base_hex}} (size: 0x{{dev['size']:X}}) ===\\033[0m")
            if not regs:
                print("  (No discrete registers declared in DTS)")
                continue

            print(f"  {{'Offset':<8}} {{'Address':<12}} {{'Register':<24}} {{'Dir':<5}} {{'Value (Hex)':<14}} {{'Value (Dec)':<12}}")
            print("  " + "-" * 80)

            for reg in regs:
                addr = dev["base_addr"] + reg["offset"]
                val_str = "[Unavailable]"
                dec_str = "-"

                # 1. Try reading from inferior process memory (for fixed mapping / /dev/mem)
                read_success = False
                if inferior:
                    try:
                        mem = inferior.read_memory(addr, 4)
                        val = struct.unpack("<I", mem)[0]
                        val_str = f"0x{{val:08X}}"
                        dec_str = f"{{val}}"
                        read_success = True
                    except gdb.MemoryError:
                        pass
                    except Exception as e:
                        val_str = f"[Err: {{e}}]"
                        dec_str = "-"
                        read_success = True

                # 2. Fallback: Read directly from F-BB simulation shared memory (for dynamic UIO mmap)
                if not read_success:
                    shm_val = None
                    try:
                        if os.path.exists(FBB_SHM_FILE):
                            with open(FBB_SHM_FILE, "rb") as sf:
                                sf.seek(reg["offset"])
                                raw = sf.read(4)
                                if len(raw) == 4:
                                    shm_val = struct.unpack("<I", raw)[0]
                    except Exception:
                        pass

                    if shm_val is not None:
                        val_str = f"0x{{shm_val:08X}}"
                        dec_str = f"{{shm_val}}"
                    else:
                        val_str = "\\033[33m[Unmapped]\\033[0m"
                        dec_str = "-"

                direction = reg.get("direction", "RW")
                dir_color = "\\033[32m" if direction == "RW" else ("\\033[34m" if direction == "RO" else "\\033[35m")
                dir_formatted = f"{{dir_color}}{{direction:<5}}\\033[0m"
                print(f"  0x{{reg['offset']:04X}}   0x{{addr:08X}}   {{reg['name']:<24}} {{dir_formatted}} {{val_str:<14}} {{dec_str:<12}}")

        if not found_any:
            print(f"No F-BB devices matched filter '{{filter_str}}'. Use 'fbb-info' to list all devices.")


class FbbWriteCommand(gdb.Command):
    """Write a 32-bit value into an F-BB MMIO register by name or address.
Usage: fbb-write <REG_NAME|ADDRESS> <VALUE_HEX_OR_DEC>"""

    def __init__(self):
        super(FbbWriteCommand, self).__init__("fbb-write", gdb.COMMAND_DATA)

    def invoke(self, arg, from_tty):
        args = arg.strip().split()
        if len(args) != 2:
            print("Usage: fbb-write <REG_NAME|ADDRESS> <VALUE_HEX_OR_DEC>")
            return

        target, val_str = args[0], args[1]
        try:
            val = int(val_str, 0) & 0xFFFFFFFF
        except ValueError:
            print(f"Error: Invalid value '{{val_str}}'")
            return

        addr = None
        reg_name = None
        reg_offset = None

        # Check if target is numeric address
        if target.startswith("0x") or target.startswith("0X") or target.isdigit():
            try:
                addr = int(target, 0)
                reg_name = f"0x{{addr:08X}}"
                # Search matching device offset
                for dev in FBB_DEVICES:
                    if dev["base_addr"] <= addr < (dev["base_addr"] + dev["size"]):
                        reg_offset = addr - dev["base_addr"]
                        break
            except ValueError:
                pass

        if addr is None:
            target_upper = target.upper()
            for dev in FBB_DEVICES:
                for reg in dev.get("registers", []):
                    if reg["name"].upper() == target_upper or f"{{dev['name'].upper()}}_{{reg['name'].upper()}}" == target_upper:
                        addr = dev["base_addr"] + reg["offset"]
                        reg_offset = reg["offset"]
                        reg_name = f"{{dev['name']}}::{{reg['name']}}"
                        break
                if addr is not None:
                    break

        if addr is None and reg_offset is None:
            print(f"Error: Register or address '{{target}}' not found in DTS.")
            return

        inferior = gdb.selected_inferior() if hasattr(gdb, "selected_inferior") else None

        wrote_mem = False
        if inferior and addr:
            try:
                inferior.write_memory(addr, struct.pack("<I", val), 4)
                wrote_mem = True
            except gdb.MemoryError:
                pass
            except Exception:
                pass

        wrote_shm = False
        if reg_offset is not None:
            try:
                if os.path.exists(FBB_SHM_FILE):
                    with open(FBB_SHM_FILE, "r+b") as sf:
                        sf.seek(reg_offset)
                        sf.write(struct.pack("<I", val))
                        wrote_shm = True
            except Exception:
                pass

        if wrote_mem or wrote_shm:
            target_desc = reg_name if reg_name else f"0x{{addr:08X}}"
            print(f"\\033[32m[F-BB GDB] Successfully wrote 0x{{val:08X}} ({{val}}) to {{target_desc}}\\033[0m")
        else:
            print(f"\\033[31m[F-BB GDB] Write failed: Address 0x{{addr:08X}} is unmapped and simulation SHM is not accessible.\\033[0m")


class FbbFdsCommand(gdb.Command):
    """List virtual file descriptors and devices intercepted by F-BB C-Shim.
Usage: fbb-fds"""

    def __init__(self):
        super(FbbFdsCommand, self).__init__("fbb-fds", gdb.COMMAND_FILES)

    def invoke(self, arg, from_tty):
        print("\\n\\033[1;36m=== F-BB Intercepted Devices & Virtual FDs ===\\033[0m")
        for dev in FBB_DEVICES:
            dev_type = dev["type"]
            base = f"0x{{dev['base_addr']:08X}}" if dev['base_addr'] else "N/A"
            print(f"  * Node: {{dev['name']:<20}} Type: {{dev_type:<8}} Base: {{base:<12}} Size: 0x{{dev['size']:X}}")
        print("  * System calls intercepted: open, read, write, ioctl, mmap, munmap, close, socket, bind, connect\\n")


class FbbInfoCommand(gdb.Command):
    """Show F-BB Scenario & Hardware Target information.
Usage: fbb-info"""

    def __init__(self):
        super(FbbInfoCommand, self).__init__("fbb-info", gdb.COMMAND_STATUS)

    def invoke(self, arg, from_tty):
        print(f"\\n\\033[1;32m[FPGA-BoardlessBench GDB Extension]\\033[0m")
        print(f"  Target Model: {{FBB_MODEL_NAME}}")
        print(f"  Active Devices: {{len(FBB_DEVICES)}}")
        total_regs = sum(len(d.get('registers', [])) for d in FBB_DEVICES)
        print(f"  Total MMIO Registers: {{total_regs}}")
        print("  Available F-BB commands:")
        print("    \\033[1;33mfbb-regs [filter]\\033[0m     - Display MMIO registers with live memory values")
        print("    \\033[1;33mfbb-write <reg> <val>\\033[0m - Write 32-bit value to register by name or address")
        print("    \\033[1;33mfbb-fds\\033[0m              - Display intercepted virtual device list")
        print("    \\033[1;33mfbb-info\\033[0m             - Show this overview message\\n")


# Register GDB commands
try:
    FbbRegsCommand()
    FbbWriteCommand()
    FbbFdsCommand()
    FbbInfoCommand()
    print("\\033[1;32m[F-BB] GDB Extension loaded for model: " + FBB_MODEL_NAME + ". Type 'fbb-info' or 'fbb-regs' to inspect.\\033[0m")
except Exception as e:
    pass
'''
        return script_content
