/* Auto-generated Device Config from DTS */
#ifndef VFPGA_DEVICE_CONFIG_H
#define VFPGA_DEVICE_CONFIG_H

/* Device Paths */
#ifndef FBB_DEV_PATH_VFPGA_UART
#define FBB_DEV_PATH_VFPGA_UART "/dev/ttyUL0"
#endif
#ifndef FBB_DEV_PATH_VFPGA_UART_0
#define FBB_DEV_PATH_VFPGA_UART_0 FBB_DEV_PATH_VFPGA_UART
#endif
#ifndef FBB_DEV_PATH_VFPGA_GPIO
#define FBB_DEV_PATH_VFPGA_GPIO "/dev/uio0"
#endif
#ifndef FBB_DEV_PATH_VFPGA_GPIO_0
#define FBB_DEV_PATH_VFPGA_GPIO_0 FBB_DEV_PATH_VFPGA_GPIO
#endif
#ifndef FBB_DEV_PATH_VFPGA_CUSTOM
#define FBB_DEV_PATH_VFPGA_CUSTOM "/dev/uio1"
#endif
#ifndef FBB_DEV_PATH_VFPGA_CUSTOM_0
#define FBB_DEV_PATH_VFPGA_CUSTOM_0 FBB_DEV_PATH_VFPGA_CUSTOM
#endif
#endif
